answering/urls.py
from django.urls import path

from answering.views import index_view, message_overview, task_template_view

app_name = "answering"

urlpatterns = [
    path("task/<int:pk>/", task_template_view, name="task-view"),
    path("messages/<uuid:pk>/", message_overview, name="messages"),
    path("", index_view, name="index"),
]

core/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("classifier/", include("classifier.urls")),
]

answering/models.py
from uuid import uuid4

from django.contrib.auth.models import Group
from django.db import models
from django.utils.translation import gettext as _
from model_utils.models import TimeStampedModel

from context.models import Realm

# Create your models here.


class Inbox(models.Model):
    uuid = models.UUIDField(default=uuid4, primary_key=True)
    secret = models.CharField(max_length=100)
    name = models.CharField(max_length=100)

    group = models.ForeignKey(Group, models.CASCADE)
    tasks: models.QuerySet["TaskTemplate"]

    def __str__(self) -> str:
        return self.name


class OpenaAIAuth(models.Model):
    group = models.ForeignKey(Group, models.CASCADE)
    api_key = models.CharField(max_length=500)


class OutputWebhook(models.Model):
    class Auth(models.TextChoices):
        DIGEST = "digest", _("Digest")
        BASIC = "basic", _("Basic")
        NONE = "none", _("None")

    name = models.CharField(max_length=100)
    url = models.CharField(max_length=1000)
    headers = models.JSONField(default=dict)

    auth_type = models.CharField(
        max_length=120, choices=Auth.choices, default=Auth.NONE
    )

    auth_user = models.CharField(max_length=120)
    auth_credential = models.CharField(max_length=120)

    def __str__(self) -> str:
        return self.name


class TaskTemplate(models.Model):
    inbox = models.ForeignKey(Inbox, models.CASCADE, related_name="tasks")
    webhook = models.ForeignKey(OutputWebhook, models.CASCADE, blank=True, null=True)
    fallback = models.BooleanField()

    name = models.CharField(max_length=300)

    generate_answer = models.BooleanField()

    lepton_url = models.CharField(max_length=1000, blank=True)

    use_openai = models.BooleanField(default=False)

    model_config = models.JSONField(default=dict)

    use_openai = models.BooleanField(default=False)

    prompt_template = models.TextField(blank=True)

    default_answer = models.TextField(blank=True)

    max_tokens = models.IntegerField(default=720)

    realm = models.ForeignKey(Realm, models.CASCADE, blank=True, null=True)

    samples: models.QuerySet["SampleTask"]

    def __str__(self) -> str:
        return self.name


class SampleTask(models.Model):
    template = models.ForeignKey(TaskTemplate, models.CASCADE, related_name="samples")

    subject = models.CharField(max_length=1024)
    content = models.TextField()

    def __str__(self) -> str:
        return self.subject


class InputMessage(TimeStampedModel):
    inbox = models.ForeignKey(Inbox, models.CASCADE)

    subject = models.CharField(max_length=1024)
    content = models.TextField()

    sender = models.EmailField(blank=True)

    processed_at = models.DateTimeField(null=True, blank=True)

    errors: models.QuerySet["ProcessError"]

    def __str__(self) -> str:
        return self.subject


class MessageClassification(TimeStampedModel):
    message = models.ForeignKey(InputMessage, models.CASCADE)
    task = models.ForeignKey(TaskTemplate, models.SET_NULL, null=True, blank=True)


class ProcessError(TimeStampedModel):
    message = models.ForeignKey(InputMessage, models.CASCADE, related_name="errors")
    timestamp = models.DateTimeField(auto_now_add=True)

    name = models.TextField()
    trace = models.TextField()


class OutputMessage(TimeStampedModel):
    input = models.ForeignKey(InputMessage, models.CASCADE)
    task = models.ForeignKey(TaskTemplate, models.CASCADE)

    subject = models.CharField(max_length=1024)
    content = models.TextField()

answering/forms.py
from django import forms


class InputForm(forms.Form):
    subject = forms.CharField(label="Betreff")
    content = forms.CharField(widget=forms.Textarea, label="Inhalt")

answering/views.py
import json

from django.contrib.auth.decorators import login_required
from django.core.exceptions import PermissionDenied
from django.core.paginator import Paginator
from django.http.request import HttpRequest
from django.http.response import JsonResponse
from django.shortcuts import render

from answering.forms import InputForm
from answering.models import Inbox, InputMessage, OutputMessage, TaskTemplate
from answering.process import write_answer
from context.models import Sentence
from context.services import extract_context


def incoming_message(request: HttpRequest, uuid):
    inbox = Inbox.objects.get(uuid=uuid)

    if request.headers.get("secret") != inbox.secret:
        raise PermissionDenied()

    data = json.loads(request.body)

    message = InputMessage.objects.create(
        inbox=inbox,
        subject=data.get("subject"),
        content=data.get("content"),
        sender=data.get("sender"),
    )

    return JsonResponse({"id": message.pk})


@login_required
def task_template_view(request, pk: int):
    task_template = TaskTemplate.objects.get(pk=pk)
    inbox = task_template.inbox
    group = task_template.inbox.group

    if not request.user.groups.filter(pk=group.pk).exists():
        raise PermissionDenied("You don't have access to this task")

    form = InputForm()

    if request.method == "POST":
        form = InputForm(request.POST)
        if form.is_valid():
            input = InputMessage.objects.create(
                inbox=task_template.inbox,
                subject=form.cleaned_data["subject"],
                content=form.cleaned_data["content"],
            )
            subject, message, hits = write_answer(
                task_template,
                input.subject,
                input.content,
            )

            results = []
            for result in hits:
                sentence = Sentence.objects.get(pk=result.id)
                results.append(
                    {
                        "distance": result.distance,
                        "sentence": extract_context(
                            sentence.document.content,
                            sentence.start_position,
                            sentence.length,
                            500,
                        ),
                        "id": sentence.pk,
                        "meta": sentence.document.meta,
                    }
                )
            OutputMessage.objects.create(
                input=input,
                task=task_template,
                subject=subject,
                content=message,
            )
            return JsonResponse(
                {"subject": subject, "message": message, "results": results}
            )

    return render(
        request,
        "answering/task_form.html",
        {"form": form, "task": task_template, "inbox": inbox},
    )


def index_view(request):
    return render(request, "index.html", {})


def message_overview(request, pk):
    inbox = Inbox.objects.get(pk=pk)
    group = inbox.group

    if not request.user.groups.filter(pk=group.pk).exists():
        raise PermissionDenied("You don't have access to this task")
    messages = InputMessage.objects.filter(inbox=inbox)

    page_number = request.GET.get("page", 1)
    p = Paginator(messages, 20)

    return render(
        request,
        "answering/messages.html",
        {
            "page": p.get_page(page_number),
            "inbox": inbox,
        },
    )

answering/templates/answering/inbox_base.html
{% extends 'base.html' %}

{% load django_bootstrap5 static %}

{% block top %}
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">{{inbox.name}}</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        {% for task in inbox.tasks.all %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'answering:task-view' task.pk %}">{{task.name}}</a>
        </li>
        {% endfor %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'answering:messages' inbox.pk %}">Antworten</a>
        </li>
      </ul>
    </div>
  </div>
</nav>
{% endblock %}

answering/templates/answering/messages.html
{% extends 'answering/inbox_base.html' %}

{% load django_bootstrap5  static %}
{% block title %}{{inbox.name}}{% endblock %}

{% block content %}
<h2> {{inbox.name}}: Fragen & Antworten</h2>
{% for message in page %}
<div class="question-group">
  <h3>Frage</h3>
  <p class="message question">{{message.content}}</p>
  {% for answer in message.outputmessage_set.all %}
  <h4>Antwort ({{answer.task.name}})</h4>
  <p class="message answer">{{answer.content}}</p>
  {% empty %}
  <p>Fehler bei der Beantwortung</p>
  {% endfor %}
</div>
{% endfor %}
{% bootstrap_pagination page %}
{% endblock content %}

answering/templates/answering/task_form.html
{% extends 'answering/inbox_base.html' %}
{% load django_bootstrap5  static %}
{% block title %}{{task.name}} | {{inbox.name}}{% endblock %}


{% block content %}
<h2>{{task.name}}</h2>

<form action="" method="post" id="inputForm" class="row">
  {% csrf_token %}
  {% bootstrap_form form layout='horizontal' %}
  <div class="col-auto">
  {% bootstrap_button button_type="submit" content="Los" %}
  </div>
</form>
<hr/>

<h3>Output</h3>
<div class="spinner-border d-none" role="status">
  <span class="visually-hidden">Loading...</span>
</div>

<textarea rows="10" class="form-control" id="outputArea"></textarea>

<h3 class="mt-2">Kontext</h3>
<div id="context"></div>

{% endblock %}

{% block scripts %}
<script src="{% static "js/task_view.js" %}">
</script>
{% endblock %}